services:
  - type: web
    name: latex-resume-api
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: true
